name: Docker

on:
  push:
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - *

env:
  IMAGE_NAME: quote-wall

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Private Registry
        uses: docker/login-action@v1
        with:
          registry: registry.vatcan.ca
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag image

      - name: Push image
        run: |
          IMAGE_ID=registry.vatcan.ca/winnipegfir/quote-wall

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention for tags, and `beta` for branches
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && LATEST=latest
          [[ "${{ github.ref }}" == "refs/heads/"* ]] && LATEST=staging

          echo IMAGE_ID=$IMAGE_ID
          echo LATEST=$LATEST
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && echo REF=$REF

          docker tag image $IMAGE_ID:$LATEST
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && docker tag image $IMAGE_ID:$REF
          docker push --all-tags $IMAGE_ID



      - name: Update rancher deployment on live website
        if: github.ref == 'refs/heads/master'
        uses: th0th/rancher-redeploy-workload@v0.9
        env:
          RANCHER_BEARER_TOKEN: ${{ secrets.RANCHER_BEARER_TOKEN }}
          RANCHER_CLUSTER_ID: c-k4z5b
          RANCHER_NAMESPACE: deployment:quote-wall
          RANCHER_PROJECT_ID: p-h6svk
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_WORKLOADS: 'web'
