name: Docker

on:
  push:
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Private Registry
        uses: docker/login-action@v1
        with:
          registry: registry.vatcan.ca
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: registry.vatcan.ca/winnipegfir/quote-wall
          tags: |
            type=raw,value=staging,enable=${{ startsWith(github.ref, 'refs/heads/') }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update rancher deployment on live website
        if: startsWith(github.ref, 'refs/tags/')
        uses: th0th/rancher-redeploy-workload@v0.9
        env:
          RANCHER_BEARER_TOKEN: ${{ secrets.RANCHER_BEARER_TOKEN }}
          RANCHER_CLUSTER_ID: c-k4z5b
          RANCHER_NAMESPACE: quote-wall
          RANCHER_PROJECT_ID: p-h6svk
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_WORKLOADS: 'web,queue-worker'
